version: "2"
services:

  db:
    image: postgres
    container_name: db
    expose:
      - "5432"

  web:
    build: .
    container_name: home-learning 
    hostname: home-learning
    volumes:
      - ./:/root/dev
    ports:
      - "33:22"
      - "1900:1900/udp"
      - "52:52"
      - "52:52/udp"
    working_dir: /root/dev
    command: bash -c "./init-script.sh"
    links:
      - db
